/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author luish
 */
public class Tela_Janela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public Tela_Janela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu_Bar = new javax.swing.JMenuBar();
        MCadastrar = new javax.swing.JMenu();
        Menu_Cliente = new javax.swing.JMenuItem();
        Menu_Produto = new javax.swing.JMenuItem();
        Menu_Sair = new javax.swing.JMenuItem();
        MClientes = new javax.swing.JMenu();
        MProdutos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(0, 52, 86));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        MCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MCadastrar.setForeground(new java.awt.Color(204, 204, 204));
        MCadastrar.setText("Cadastrar");
        MCadastrar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        Menu_Cliente.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Menu_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icon/Cadastrar.png"))); // NOI18N
        Menu_Cliente.setText("Cliente");
        Menu_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ClienteActionPerformed(evt);
            }
        });
        MCadastrar.add(Menu_Cliente);

        Menu_Produto.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Menu_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icon/Clientes.png"))); // NOI18N
        Menu_Produto.setText("Produto");
        MCadastrar.add(Menu_Produto);

        Menu_Sair.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Menu_Sair.setText("Sair");
        MCadastrar.add(Menu_Sair);

        Menu_Bar.add(MCadastrar);

        MClientes.setForeground(new java.awt.Color(204, 204, 204));
        MClientes.setText("Consultar Clientes");
        MClientes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Menu_Bar.add(MClientes);

        MProdutos.setForeground(new java.awt.Color(204, 204, 204));
        MProdutos.setText("Vender Produtos");
        MProdutos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Menu_Bar.add(MProdutos);

        setJMenuBar(Menu_Bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Janela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MCadastrar;
    private javax.swing.JMenu MClientes;
    private javax.swing.JMenu MProdutos;
    private javax.swing.JMenuBar Menu_Bar;
    private javax.swing.JMenuItem Menu_Cliente;
    private javax.swing.JMenuItem Menu_Produto;
    private javax.swing.JMenuItem Menu_Sair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
