/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author luish
 */
public class Tela_Cadastro_Cliente extends javax.swing.JFrame {

    /** Creates new form Cadastro_Cliente */
    public Tela_Cadastro_Cliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Fundo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_CadastroCliente = new javax.swing.JLabel();
        Label_DataN = new javax.swing.JLabel();
        Label_Nome = new javax.swing.JLabel();
        Label_Endereco = new javax.swing.JLabel();
        Label_Telefone = new javax.swing.JLabel();
        Label_email = new javax.swing.JLabel();
        Label_Altura = new javax.swing.JLabel();
        Label_Peso = new javax.swing.JLabel();
        Label_Indicacao = new javax.swing.JLabel();
        Label_JiuJitsu = new javax.swing.JLabel();
        Label_Matricula = new javax.swing.JLabel();
        Label_TipoTreino = new javax.swing.JLabel();
        Label_Cardiaco = new javax.swing.JLabel();
        Label_PRespiratorio = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TextFild_Nome = new javax.swing.JTextField();
        TextFild_DataN = new javax.swing.JTextField();
        TextFild_Endereco = new javax.swing.JTextField();
        TextFild_Telefone = new javax.swing.JTextField();
        TextFild_Email = new javax.swing.JTextField();
        TextFild_Altura = new javax.swing.JTextField();
        TextFild_Peso = new javax.swing.JTextField();
        TextFild_Maricula = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Button_Validar = new javax.swing.JButton();
        Button_Cadastrar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        ComboBox_indicacao = new javax.swing.JComboBox<>();
        ComboBox_JiuJisu = new javax.swing.JComboBox<>();
        ComboBox_TipoTreino = new javax.swing.JComboBox<>();
        ComboBox_PCardiaco = new javax.swing.JComboBox<>();
        ComboBox_PRespiratorio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Cliente");

        Painel_Fundo.setBackground(new java.awt.Color(51, 51, 51));
        Painel_Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Painel_Fundo.setPreferredSize(new java.awt.Dimension(800, 600));

        jSeparator1.setForeground(new java.awt.Color(153, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Label_CadastroCliente.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Label_CadastroCliente.setForeground(new java.awt.Color(204, 204, 204));
        Label_CadastroCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_CadastroCliente.setText("Cadastro do Cliente");

        Label_DataN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_DataN.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataN.setText("Data de Nascimento:");

        Label_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Nome.setForeground(new java.awt.Color(204, 204, 204));
        Label_Nome.setText("Nome:");

        Label_Endereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Endereco.setForeground(new java.awt.Color(204, 204, 204));
        Label_Endereco.setText("Endereço:");

        Label_Telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Telefone.setForeground(new java.awt.Color(204, 204, 204));
        Label_Telefone.setText("Telefone:");

        Label_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_email.setForeground(new java.awt.Color(204, 204, 204));
        Label_email.setText("e-mail:");

        Label_Altura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Altura.setForeground(new java.awt.Color(204, 204, 204));
        Label_Altura.setText("Altura:");

        Label_Peso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Peso.setForeground(new java.awt.Color(204, 204, 204));
        Label_Peso.setText("Peso:");

        Label_Indicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Indicacao.setForeground(new java.awt.Color(204, 204, 204));
        Label_Indicacao.setText("Indicação de Cliente ?");

        Label_JiuJitsu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_JiuJitsu.setForeground(new java.awt.Color(204, 204, 204));
        Label_JiuJitsu.setText("Jiu-Jitsu:");

        Label_Matricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Matricula.setForeground(new java.awt.Color(204, 204, 204));
        Label_Matricula.setText("Numero da Matricula:");

        Label_TipoTreino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_TipoTreino.setForeground(new java.awt.Color(204, 204, 204));
        Label_TipoTreino.setText("Tipo de Treino:");

        Label_Cardiaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Cardiaco.setForeground(new java.awt.Color(204, 204, 204));
        Label_Cardiaco.setText("Problemas Cardiacos?");

        Label_PRespiratorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_PRespiratorio.setForeground(new java.awt.Color(204, 204, 204));
        Label_PRespiratorio.setText("Problemas Respiratórios?");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        TextFild_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFild_NomeActionPerformed(evt);
            }
        });

        TextFild_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFild_EmailActionPerformed(evt);
            }
        });

        TextFild_Altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFild_AlturaActionPerformed(evt);
            }
        });

        TextFild_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFild_PesoActionPerformed(evt);
            }
        });

        TextFild_Maricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFild_MariculaActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Button_Validar.setBackground(new java.awt.Color(204, 204, 204));
        Button_Validar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Validar.setForeground(new java.awt.Color(102, 102, 102));
        Button_Validar.setText("Validar");
        Button_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ValidarActionPerformed(evt);
            }
        });

        Button_Cadastrar.setBackground(new java.awt.Color(204, 204, 204));
        Button_Cadastrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Button_Cadastrar.setForeground(new java.awt.Color(102, 102, 102));
        Button_Cadastrar.setText("Cadastrar");
        Button_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CadastrarActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        ComboBox_indicacao.setEditable(true);
        ComboBox_indicacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBox_indicacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        ComboBox_indicacao.setRequestFocusEnabled(true);
        ComboBox_indicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_indicacaoActionPerformed(evt);
            }
        });

        ComboBox_JiuJisu.setEditable(true);
        ComboBox_JiuJisu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBox_JiuJisu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        ComboBox_JiuJisu.setRequestFocusEnabled(true);
        ComboBox_JiuJisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_JiuJisuActionPerformed(evt);
            }
        });

        ComboBox_TipoTreino.setEditable(true);
        ComboBox_TipoTreino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBox_TipoTreino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musculação", "Aerobica", "Ambos" }));
        ComboBox_TipoTreino.setRequestFocusEnabled(true);
        ComboBox_TipoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_TipoTreinoActionPerformed(evt);
            }
        });

        ComboBox_PCardiaco.setEditable(true);
        ComboBox_PCardiaco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBox_PCardiaco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        ComboBox_PCardiaco.setRequestFocusEnabled(true);
        ComboBox_PCardiaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_PCardiacoActionPerformed(evt);
            }
        });

        ComboBox_PRespiratorio.setEditable(true);
        ComboBox_PRespiratorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBox_PRespiratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        ComboBox_PRespiratorio.setRequestFocusEnabled(true);
        ComboBox_PRespiratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_PRespiratorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_FundoLayout = new javax.swing.GroupLayout(Painel_Fundo);
        Painel_Fundo.setLayout(Painel_FundoLayout);
        Painel_FundoLayout.setHorizontalGroup(
            Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_FundoLayout.createSequentialGroup()
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_CadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Painel_FundoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Button_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Painel_FundoLayout.createSequentialGroup()
                                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFild_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFild_DataN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFild_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFild_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Nome)
                                    .addComponent(Label_DataN)
                                    .addComponent(Label_Endereco)
                                    .addComponent(Label_Telefone)
                                    .addComponent(Label_email)
                                    .addComponent(TextFild_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextFild_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_Altura)
                                            .addComponent(TextFild_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_Peso)
                                            .addComponent(Label_Indicacao)
                                            .addComponent(ComboBox_indicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_Matricula)
                                            .addComponent(TextFild_Maricula, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(Button_Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_JiuJitsu)
                                    .addComponent(ComboBox_JiuJisu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Cardiaco)
                                    .addComponent(ComboBox_PCardiaco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_PRespiratorio)
                                    .addComponent(ComboBox_PRespiratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ComboBox_TipoTreino, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(Label_TipoTreino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(159, 159, 159))
        );
        Painel_FundoLayout.setVerticalGroup(
            Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_FundoLayout.createSequentialGroup()
                .addComponent(Label_CadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_FundoLayout.createSequentialGroup()
                                .addComponent(Label_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_DataN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_DataN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Label_Endereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Label_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_FundoLayout.createSequentialGroup()
                                .addComponent(Label_Altura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Peso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Indicacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_indicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Matricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFild_Maricula, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_Validar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addComponent(Label_JiuJitsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_JiuJisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_TipoTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_TipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Cardiaco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_PCardiaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_PRespiratorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_PRespiratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Painel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFild_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFild_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFild_EmailActionPerformed

    private void TextFild_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFild_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFild_NomeActionPerformed

    private void TextFild_AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFild_AlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFild_AlturaActionPerformed

    private void TextFild_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFild_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFild_PesoActionPerformed

    private void ComboBox_indicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_indicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_indicacaoActionPerformed

    private void TextFild_MariculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFild_MariculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFild_MariculaActionPerformed

    private void Button_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CadastrarActionPerformed

    private void ComboBox_JiuJisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_JiuJisuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_JiuJisuActionPerformed

    private void ComboBox_TipoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_TipoTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_TipoTreinoActionPerformed

    private void ComboBox_PCardiacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_PCardiacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_PCardiacoActionPerformed

    private void ComboBox_PRespiratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_PRespiratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_PRespiratorioActionPerformed

    private void Button_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ValidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cadastrar;
    private javax.swing.JButton Button_Validar;
    private javax.swing.JComboBox<String> ComboBox_JiuJisu;
    private javax.swing.JComboBox<String> ComboBox_PCardiaco;
    private javax.swing.JComboBox<String> ComboBox_PRespiratorio;
    private javax.swing.JComboBox<String> ComboBox_TipoTreino;
    private javax.swing.JComboBox<String> ComboBox_indicacao;
    private javax.swing.JLabel Label_Altura;
    private javax.swing.JLabel Label_CadastroCliente;
    private javax.swing.JLabel Label_Cardiaco;
    private javax.swing.JLabel Label_DataN;
    private javax.swing.JLabel Label_Endereco;
    private javax.swing.JLabel Label_Indicacao;
    private javax.swing.JLabel Label_JiuJitsu;
    private javax.swing.JLabel Label_Matricula;
    private javax.swing.JLabel Label_Nome;
    private javax.swing.JLabel Label_PRespiratorio;
    private javax.swing.JLabel Label_Peso;
    private javax.swing.JLabel Label_Telefone;
    private javax.swing.JLabel Label_TipoTreino;
    private javax.swing.JLabel Label_email;
    private javax.swing.JPanel Painel_Fundo;
    private javax.swing.JTextField TextFild_Altura;
    private javax.swing.JTextField TextFild_DataN;
    private javax.swing.JTextField TextFild_Email;
    private javax.swing.JTextField TextFild_Endereco;
    private javax.swing.JTextField TextFild_Maricula;
    private javax.swing.JTextField TextFild_Nome;
    private javax.swing.JTextField TextFild_Peso;
    private javax.swing.JTextField TextFild_Telefone;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
