/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author luish
 */
public class Tela_Login extends javax.swing.JFrame {

    /** Creates new form Tela_Login */
    
    String nome,

    /**
     * Creates new form Tela_Login
     */
    senha;
    public Tela_Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        Label_Login = new javax.swing.JLabel();
        TextField_Usuario = new javax.swing.JTextField();
        PasswordField_Senha = new javax.swing.JPasswordField();
        Label_Usuario = new javax.swing.JLabel();
        Label_Senha = new javax.swing.JLabel();
        Button_Entrar = new javax.swing.JButton();
        Label_login_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(450, 650));
        setResizable(false);

        Fundo.setBackground(new java.awt.Color(51, 51, 51));
        Fundo.setPreferredSize(new java.awt.Dimension(450, 650));

        Label_Login.setBackground(new java.awt.Color(153, 153, 153));
        Label_Login.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Label_Login.setForeground(new java.awt.Color(255, 255, 255));
        Label_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Login.setText("Login");

        TextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UsuarioActionPerformed(evt);
            }
        });

        PasswordField_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_SenhaActionPerformed(evt);
            }
        });

        Label_Usuario.setBackground(new java.awt.Color(153, 153, 153));
        Label_Usuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_Usuario.setText("Usuário:");

        Label_Senha.setBackground(new java.awt.Color(153, 153, 153));
        Label_Senha.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Label_Senha.setForeground(new java.awt.Color(255, 255, 255));
        Label_Senha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_Senha.setText("Senha:");
        Label_Senha.setToolTipText("");

        Button_Entrar.setBackground(new java.awt.Color(255, 255, 255));
        Button_Entrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Button_Entrar.setForeground(new java.awt.Color(51, 51, 51));
        Button_Entrar.setText("Entrar");
        Button_Entrar.setActionCommand("Button_Entrar");
        Button_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EntrarActionPerformed(evt);
            }
        });

        Label_login_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/esportes-e-competicao.png"))); // NOI18N

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Label_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_Usuario)
                            .addComponent(PasswordField_Senha)
                            .addComponent(Label_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Button_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(Label_login_Icon)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Label_login_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(Label_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Label_Senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Button_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(396, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_UsuarioActionPerformed

    private void Button_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EntrarActionPerformed
        // TODO add your handling code here:
        nome = TextField_Usuario.getText();
        senha = PasswordField_Senha.getText();
        
    }//GEN-LAST:event_Button_EntrarActionPerformed

    private void PasswordField_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Entrar;
    private javax.swing.JPanel Fundo;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Senha;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_login_Icon;
    private javax.swing.JPasswordField PasswordField_Senha;
    private javax.swing.JTextField TextField_Usuario;
    // End of variables declaration//GEN-END:variables

}
