/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author luish
 */
public class Tela_Cadastro_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Produtos
     */
    public Tela_Cadastro_Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Fundo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_CadastrodeProdutos = new javax.swing.JLabel();
        Label_nome = new javax.swing.JLabel();
        Label_Valor = new javax.swing.JLabel();
        Label_Quantidade = new javax.swing.JLabel();
        Label_TIpo = new javax.swing.JLabel();
        Label_RS = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TextField_Nome = new javax.swing.JTextField();
        TextField_RS = new javax.swing.JTextField();
        TextField_Quantidade = new javax.swing.JTextField();
        ComboBox_Tipos = new javax.swing.JComboBox<>();
        Button_Cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);

        Painel_Fundo.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Label_CadastrodeProdutos.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        Label_CadastrodeProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_CadastrodeProdutos.setText("Cadastro de Produtos");

        Label_nome.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Label_nome.setText("Nome:");

        Label_Valor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Label_Valor.setText("Valor:");

        Label_Quantidade.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Label_Quantidade.setText("Quantidade:");

        Label_TIpo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Label_TIpo.setText("Tipo:");

        Label_RS.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Label_RS.setText("R$:");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        ComboBox_Tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suplementos", "Acessórios", "Bebidas" }));

        Button_Cadastrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Button_Cadastrar.setText("Cadastrar");
        Button_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_FundoLayout = new javax.swing.GroupLayout(Painel_Fundo);
        Painel_Fundo.setLayout(Painel_FundoLayout);
        Painel_FundoLayout.setHorizontalGroup(
            Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_FundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_CadastrodeProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addComponent(TextField_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Button_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_nome)
                    .addComponent(Label_Valor)
                    .addComponent(Label_Quantidade)
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addComponent(Label_TIpo)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_FundoLayout.createSequentialGroup()
                        .addComponent(Label_RS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Painel_FundoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Painel_FundoLayout.setVerticalGroup(
            Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_FundoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Label_CadastrodeProdutos)
                .addGap(27, 27, 27)
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_TIpo))
                .addGap(18, 18, 18)
                .addComponent(Label_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_RS)
                    .addComponent(TextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Quantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(Painel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Painel_FundoLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(308, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cadastrar;
    private javax.swing.JComboBox<String> ComboBox_Tipos;
    private javax.swing.JLabel Label_CadastrodeProdutos;
    private javax.swing.JLabel Label_Quantidade;
    private javax.swing.JLabel Label_RS;
    private javax.swing.JLabel Label_TIpo;
    private javax.swing.JLabel Label_Valor;
    private javax.swing.JLabel Label_nome;
    private javax.swing.JPanel Painel_Fundo;
    private javax.swing.JTextField TextField_Nome;
    private javax.swing.JTextField TextField_Quantidade;
    private javax.swing.JTextField TextField_RS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
