/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import java.sql.*;
import javax.swing.JOptionPane;
import Controller.Login;
import Model.LoginBD;
import java.util.logging.Level;
import java.util.logging.Logger;
import View.Tela_Janela_Principal;
import javax.swing.ImageIcon;

/**
 *
 * @author luish
 */
public class Tela_Login extends javax.swing.JFrame {
    private Login set;
    private LoginBD verificar; 
    private Tela_Janela_Principal principal;

    /** Creates new form Tela_Login */
    
    String nome,

    /**
     * Creates new form Tela_Login
     */
    senha;
    public Tela_Login() {
        principal = new Tela_Janela_Principal();
        verificar = new LoginBD();
        set = new Login();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo1 = new View.Images.fundo();
        Label_Login = new javax.swing.JLabel();
        Label_Usuario = new javax.swing.JLabel();
        Label_Senha = new javax.swing.JLabel();
        Label_login_Icon = new javax.swing.JLabel();
        TextField_Usuario = new javax.swing.JTextField();
        PasswordField_Senha = new javax.swing.JPasswordField();
        Button_Entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(450, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        fundo1.setImg(new ImageIcon("src/View/images/Fundo01.png"));

        Label_Login.setBackground(new java.awt.Color(153, 153, 153));
        Label_Login.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Label_Login.setForeground(new java.awt.Color(0, 0, 0));
        Label_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Login.setText("Login");

        Label_Usuario.setBackground(new java.awt.Color(153, 153, 153));
        Label_Usuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Label_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Usuario.setText("Usuário:");

        Label_Senha.setBackground(new java.awt.Color(153, 153, 153));
        Label_Senha.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Label_Senha.setForeground(new java.awt.Color(0, 0, 0));
        Label_Senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Senha.setText("Senha:");
        Label_Senha.setToolTipText("");

        Label_login_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icon/logogym.png"))); // NOI18N

        TextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UsuarioActionPerformed(evt);
            }
        });

        PasswordField_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_SenhaActionPerformed(evt);
            }
        });

        Button_Entrar.setBackground(new java.awt.Color(255, 255, 255));
        Button_Entrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Button_Entrar.setForeground(new java.awt.Color(51, 51, 51));
        Button_Entrar.setText("Entrar");
        Button_Entrar.setActionCommand("Button_Entrar");
        Button_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundo1Layout = new javax.swing.GroupLayout(fundo1);
        fundo1.setLayout(fundo1Layout);
        fundo1Layout.setHorizontalGroup(
            fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo1Layout.createSequentialGroup()
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(Button_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Label_login_Icon)))
                .addContainerGap(510, Short.MAX_VALUE))
        );
        fundo1Layout.setVerticalGroup(
            fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Label_login_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Label_Usuario)
                .addGap(6, 6, 6)
                .addComponent(TextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Label_Senha)
                .addGap(6, 6, 6)
                .addComponent(PasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Button_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(fundo1);
        fundo1.setBounds(0, 0, 800, 563);

        setSize(new java.awt.Dimension(396, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_UsuarioActionPerformed

    private void Button_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EntrarActionPerformed
        // TODO add your handling code here:
        nome = TextField_Usuario.getText();
        senha = PasswordField_Senha.getText();
        try {
            verificar.verificarUsuario(nome, senha);
            if (verificar.getStatus() == true){
                principal.setVisible(true);
              this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Login e/ou usuário errado(s)","Erro",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Button_EntrarActionPerformed

    private void PasswordField_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Entrar;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Senha;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_login_Icon;
    private javax.swing.JPasswordField PasswordField_Senha;
    private javax.swing.JTextField TextField_Usuario;
    private View.Images.fundo fundo1;
    // End of variables declaration//GEN-END:variables

}
